name: Release

on:
  push:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm ci
      #- run: npm run build
      - run: npm install @semantic-release/github @semantic-release/git -D
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GIT_TOKEN }}
